/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MATRIXKBDPORTCMOCKS_H
#define _MATRIXKBDPORTCMOCKS_H

#include "unity.h"
#include "matrix_kbd_hal.h"
/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void MockDwinPortCmocks_Init(void);
void MockDwinPortCmocks_Destroy(void);
void MockDwinPortCmocks_Verify(void);




#define MatrixKbdHalPortColumnSelect_IgnoreAndReturn(cmock_retval) MatrixKbdHalPortColumnSelect_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void MatrixKbdHalPortColumnSelect_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, MatrixKbdHalErr_e cmock_to_return);
#define MatrixKbdHalPortColumnSelect_StopIgnore() MatrixKbdHalPortColumnSelect_CMockStopIgnore()
void MatrixKbdHalPortColumnSelect_CMockStopIgnore(void);
#define MatrixKbdHalPortColumnSelect_ExpectAndReturn(hal, number, cmock_retval) MatrixKbdHalPortColumnSelect_CMockExpectAndReturn(__LINE__, hal, number, cmock_retval)
void MatrixKbdHalPortColumnSelect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const void* const hal, const uint8_t number, MatrixKbdHalErr_e cmock_to_return);
typedef MatrixKbdHalErr_e (* CMOCK_MatrixKbdHalPortColumnSelect_CALLBACK)(const void* const hal, const uint8_t number, int cmock_num_calls);
void MatrixKbdHalPortColumnSelect_AddCallback(CMOCK_MatrixKbdHalPortColumnSelect_CALLBACK Callback);
void MatrixKbdHalPortColumnSelect_Stub(CMOCK_MatrixKbdHalPortColumnSelect_CALLBACK Callback);
#define MatrixKbdHalPortColumnSelect_StubWithCallback MatrixKbdHalPortColumnSelect_Stub
#define MatrixKbdHalPortColumnSelect_IgnoreArg_hal() MatrixKbdHalPortColumnSelect_CMockIgnoreArg_hal(__LINE__)
void MatrixKbdHalPortColumnSelect_CMockIgnoreArg_hal(UNITY_LINE_TYPE cmock_line);
#define MatrixKbdHalPortColumnSelect_IgnoreArg_number() MatrixKbdHalPortColumnSelect_CMockIgnoreArg_number(__LINE__)
void MatrixKbdHalPortColumnSelect_CMockIgnoreArg_number(UNITY_LINE_TYPE cmock_line);
#define MatrixKbdHalPortColumnDeselect_IgnoreAndReturn(cmock_retval) MatrixKbdHalPortColumnDeselect_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void MatrixKbdHalPortColumnDeselect_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, MatrixKbdHalErr_e cmock_to_return);
#define MatrixKbdHalPortColumnDeselect_StopIgnore() MatrixKbdHalPortColumnDeselect_CMockStopIgnore()
void MatrixKbdHalPortColumnDeselect_CMockStopIgnore(void);
#define MatrixKbdHalPortColumnDeselect_ExpectAndReturn(hal, number, cmock_retval) MatrixKbdHalPortColumnDeselect_CMockExpectAndReturn(__LINE__, hal, number, cmock_retval)
void MatrixKbdHalPortColumnDeselect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const void* const hal, const uint8_t number, MatrixKbdHalErr_e cmock_to_return);
typedef MatrixKbdHalErr_e (* CMOCK_MatrixKbdHalPortColumnDeselect_CALLBACK)(const void* const hal, const uint8_t number, int cmock_num_calls);
void MatrixKbdHalPortColumnDeselect_AddCallback(CMOCK_MatrixKbdHalPortColumnDeselect_CALLBACK Callback);
void MatrixKbdHalPortColumnDeselect_Stub(CMOCK_MatrixKbdHalPortColumnDeselect_CALLBACK Callback);
#define MatrixKbdHalPortColumnDeselect_StubWithCallback MatrixKbdHalPortColumnDeselect_Stub
#define MatrixKbdHalPortColumnDeselect_IgnoreArg_hal() MatrixKbdHalPortColumnDeselect_CMockIgnoreArg_hal(__LINE__)
void MatrixKbdHalPortColumnDeselect_CMockIgnoreArg_hal(UNITY_LINE_TYPE cmock_line);
#define MatrixKbdHalPortColumnDeselect_IgnoreArg_number() MatrixKbdHalPortColumnDeselect_CMockIgnoreArg_number(__LINE__)
void MatrixKbdHalPortColumnDeselect_CMockIgnoreArg_number(UNITY_LINE_TYPE cmock_line);
#define MatrixKbdHalPortRowStateGet_IgnoreAndReturn(cmock_retval) MatrixKbdHalPortRowStateGet_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void MatrixKbdHalPortRowStateGet_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, MatrixKbdHalErr_e cmock_to_return);
#define MatrixKbdHalPortRowStateGet_StopIgnore() MatrixKbdHalPortRowStateGet_CMockStopIgnore()
void MatrixKbdHalPortRowStateGet_CMockStopIgnore(void);
#define MatrixKbdHalPortRowStateGet_ExpectAndReturn(hal, number, data, cmock_retval) MatrixKbdHalPortRowStateGet_CMockExpectAndReturn(__LINE__, hal, number, data, cmock_retval)
void MatrixKbdHalPortRowStateGet_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const void* const hal, const uint8_t number, bool* const data, MatrixKbdHalErr_e cmock_to_return);
typedef MatrixKbdHalErr_e (* CMOCK_MatrixKbdHalPortRowStateGet_CALLBACK)(const void* const hal, const uint8_t number, bool* const data, int cmock_num_calls);
void MatrixKbdHalPortRowStateGet_AddCallback(CMOCK_MatrixKbdHalPortRowStateGet_CALLBACK Callback);
void MatrixKbdHalPortRowStateGet_Stub(CMOCK_MatrixKbdHalPortRowStateGet_CALLBACK Callback);
#define MatrixKbdHalPortRowStateGet_StubWithCallback MatrixKbdHalPortRowStateGet_Stub
#define MatrixKbdHalPortRowStateGet_ReturnThruPtr_data(data) MatrixKbdHalPortRowStateGet_CMockReturnMemThruPtr_data(__LINE__, data, sizeof(bool))
#define MatrixKbdHalPortRowStateGet_ReturnArrayThruPtr_data(data, cmock_len) MatrixKbdHalPortRowStateGet_CMockReturnMemThruPtr_data(__LINE__, data, cmock_len * sizeof(*data))
#define MatrixKbdHalPortRowStateGet_ReturnMemThruPtr_data(data, cmock_size) MatrixKbdHalPortRowStateGet_CMockReturnMemThruPtr_data(__LINE__, data, cmock_size)
void MatrixKbdHalPortRowStateGet_CMockReturnMemThruPtr_data(UNITY_LINE_TYPE cmock_line, bool const* data, size_t cmock_size);
#define MatrixKbdHalPortRowStateGet_IgnoreArg_hal() MatrixKbdHalPortRowStateGet_CMockIgnoreArg_hal(__LINE__)
void MatrixKbdHalPortRowStateGet_CMockIgnoreArg_hal(UNITY_LINE_TYPE cmock_line);
#define MatrixKbdHalPortRowStateGet_IgnoreArg_number() MatrixKbdHalPortRowStateGet_CMockIgnoreArg_number(__LINE__)
void MatrixKbdHalPortRowStateGet_CMockIgnoreArg_number(UNITY_LINE_TYPE cmock_line);
#define MatrixKbdHalPortRowStateGet_IgnoreArg_data() MatrixKbdHalPortRowStateGet_CMockIgnoreArg_data(__LINE__)
void MatrixKbdHalPortRowStateGet_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif