/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mocks.h"
#include "matrix_kbd_hal_cmock.h"


static const char* CMockString_MatrixKbdHalPortColumnDeselect = "MatrixKbdHalPortColumnDeselect";
static const char* CMockString_MatrixKbdHalPortColumnSelect = "MatrixKbdHalPortColumnSelect";
static const char* CMockString_MatrixKbdHalPortRowStateGet = "MatrixKbdHalPortRowStateGet";
static const char* CMockString_data = "data";
static const char* CMockString_hal = "hal";
static const char* CMockString_number = "number";

typedef struct _CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  MatrixKbdHalErr_e ReturnVal;
  const void* Expected_hal;
  uint8_t Expected_number;
  char IgnoreArg_hal;
  char IgnoreArg_number;

} CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE;

typedef struct _CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  MatrixKbdHalErr_e ReturnVal;
  const void* Expected_hal;
  uint8_t Expected_number;
  char IgnoreArg_hal;
  char IgnoreArg_number;

} CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE;

typedef struct _CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  MatrixKbdHalErr_e ReturnVal;
  const void* Expected_hal;
  uint8_t Expected_number;
  bool* Expected_data;
  char ReturnThruPtr_data_Used;
  bool const* ReturnThruPtr_data_Val;
  size_t ReturnThruPtr_data_Size;
  char IgnoreArg_hal;
  char IgnoreArg_number;
  char IgnoreArg_data;

} CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE;

static struct MockDwinPortCmocksInstance
{
  char MatrixKbdHalPortColumnSelect_IgnoreBool;
  MatrixKbdHalErr_e MatrixKbdHalPortColumnSelect_FinalReturn;
  char MatrixKbdHalPortColumnSelect_CallbackBool;
  CMOCK_MatrixKbdHalPortColumnSelect_CALLBACK MatrixKbdHalPortColumnSelect_CallbackFunctionPointer;
  int MatrixKbdHalPortColumnSelect_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE MatrixKbdHalPortColumnSelect_CallInstance;
  char MatrixKbdHalPortColumnDeselect_IgnoreBool;
  MatrixKbdHalErr_e MatrixKbdHalPortColumnDeselect_FinalReturn;
  char MatrixKbdHalPortColumnDeselect_CallbackBool;
  CMOCK_MatrixKbdHalPortColumnDeselect_CALLBACK MatrixKbdHalPortColumnDeselect_CallbackFunctionPointer;
  int MatrixKbdHalPortColumnDeselect_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE MatrixKbdHalPortColumnDeselect_CallInstance;
  char MatrixKbdHalPortRowStateGet_IgnoreBool;
  MatrixKbdHalErr_e MatrixKbdHalPortRowStateGet_FinalReturn;
  char MatrixKbdHalPortRowStateGet_CallbackBool;
  CMOCK_MatrixKbdHalPortRowStateGet_CALLBACK MatrixKbdHalPortRowStateGet_CallbackFunctionPointer;
  int MatrixKbdHalPortRowStateGet_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE MatrixKbdHalPortRowStateGet_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockDwinPortCmocks_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.MatrixKbdHalPortColumnSelect_CallInstance;
  if (Mock.MatrixKbdHalPortColumnSelect_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MatrixKbdHalPortColumnSelect);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.MatrixKbdHalPortColumnSelect_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.MatrixKbdHalPortColumnDeselect_CallInstance;
  if (Mock.MatrixKbdHalPortColumnDeselect_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MatrixKbdHalPortColumnDeselect);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.MatrixKbdHalPortColumnDeselect_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.MatrixKbdHalPortRowStateGet_CallInstance;
  if (Mock.MatrixKbdHalPortRowStateGet_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MatrixKbdHalPortRowStateGet);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.MatrixKbdHalPortRowStateGet_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void MockDwinPortCmocks_Init(void)
{
  MockDwinPortCmocks_Destroy();
}

void MockDwinPortCmocks_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

MatrixKbdHalErr_e MatrixKbdHalPortColumnSelect(const void* const hal, const uint8_t number)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MatrixKbdHalPortColumnSelect);
  cmock_call_instance = (CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MatrixKbdHalPortColumnSelect_CallInstance);
  Mock.MatrixKbdHalPortColumnSelect_CallInstance = CMock_Guts_MemNext(Mock.MatrixKbdHalPortColumnSelect_CallInstance);
  if (Mock.MatrixKbdHalPortColumnSelect_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.MatrixKbdHalPortColumnSelect_FinalReturn;
    memcpy((void*)(&Mock.MatrixKbdHalPortColumnSelect_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(MatrixKbdHalErr_e[sizeof(cmock_call_instance->ReturnVal) == sizeof(MatrixKbdHalErr_e) ? 1 : -1])); /* add MatrixKbdHalErr_e to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.MatrixKbdHalPortColumnSelect_CallbackBool &&
      Mock.MatrixKbdHalPortColumnSelect_CallbackFunctionPointer != NULL)
  {
    MatrixKbdHalErr_e cmock_cb_ret = Mock.MatrixKbdHalPortColumnSelect_CallbackFunctionPointer(hal, number, Mock.MatrixKbdHalPortColumnSelect_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_hal)
  {
    UNITY_SET_DETAILS(CMockString_MatrixKbdHalPortColumnSelect,CMockString_hal);
    if (cmock_call_instance->Expected_hal == NULL)
      { UNITY_TEST_ASSERT_NULL(hal, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_hal, hal, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_number)
  {
    UNITY_SET_DETAILS(CMockString_MatrixKbdHalPortColumnSelect,CMockString_number);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_number, number, cmock_line, CMockStringMismatch);
  }
  if (Mock.MatrixKbdHalPortColumnSelect_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.MatrixKbdHalPortColumnSelect_CallbackFunctionPointer(hal, number, Mock.MatrixKbdHalPortColumnSelect_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_MatrixKbdHalPortColumnSelect(CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE* cmock_call_instance, const void* const hal, const uint8_t number);
void CMockExpectParameters_MatrixKbdHalPortColumnSelect(CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE* cmock_call_instance, const void* const hal, const uint8_t number)
{
  cmock_call_instance->Expected_hal = hal;
  cmock_call_instance->IgnoreArg_hal = 0;
  cmock_call_instance->Expected_number = number;
  cmock_call_instance->IgnoreArg_number = 0;
}

void MatrixKbdHalPortColumnSelect_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, MatrixKbdHalErr_e cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE));
  CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MatrixKbdHalPortColumnSelect_CallInstance = CMock_Guts_MemChain(Mock.MatrixKbdHalPortColumnSelect_CallInstance, cmock_guts_index);
  Mock.MatrixKbdHalPortColumnSelect_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.MatrixKbdHalPortColumnSelect_IgnoreBool = (char)1;
}

void MatrixKbdHalPortColumnSelect_CMockStopIgnore(void)
{
  if(Mock.MatrixKbdHalPortColumnSelect_IgnoreBool)
    Mock.MatrixKbdHalPortColumnSelect_CallInstance = CMock_Guts_MemNext(Mock.MatrixKbdHalPortColumnSelect_CallInstance);
  Mock.MatrixKbdHalPortColumnSelect_IgnoreBool = (char)0;
}

void MatrixKbdHalPortColumnSelect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const void* const hal, const uint8_t number, MatrixKbdHalErr_e cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE));
  CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MatrixKbdHalPortColumnSelect_CallInstance = CMock_Guts_MemChain(Mock.MatrixKbdHalPortColumnSelect_CallInstance, cmock_guts_index);
  Mock.MatrixKbdHalPortColumnSelect_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_MatrixKbdHalPortColumnSelect(cmock_call_instance, hal, number);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(MatrixKbdHalErr_e[sizeof(cmock_to_return) == sizeof(MatrixKbdHalErr_e) ? 1 : -1])); /* add MatrixKbdHalErr_e to :treat_as_array if this causes an error */
}

void MatrixKbdHalPortColumnSelect_AddCallback(CMOCK_MatrixKbdHalPortColumnSelect_CALLBACK Callback)
{
  Mock.MatrixKbdHalPortColumnSelect_IgnoreBool = (char)0;
  Mock.MatrixKbdHalPortColumnSelect_CallbackBool = (char)1;
  Mock.MatrixKbdHalPortColumnSelect_CallbackFunctionPointer = Callback;
}

void MatrixKbdHalPortColumnSelect_Stub(CMOCK_MatrixKbdHalPortColumnSelect_CALLBACK Callback)
{
  Mock.MatrixKbdHalPortColumnSelect_IgnoreBool = (char)0;
  Mock.MatrixKbdHalPortColumnSelect_CallbackBool = (char)0;
  Mock.MatrixKbdHalPortColumnSelect_CallbackFunctionPointer = Callback;
}

void MatrixKbdHalPortColumnSelect_CMockIgnoreArg_hal(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MatrixKbdHalPortColumnSelect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_hal = 1;
}

void MatrixKbdHalPortColumnSelect_CMockIgnoreArg_number(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortColumnSelect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MatrixKbdHalPortColumnSelect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_number = 1;
}

MatrixKbdHalErr_e MatrixKbdHalPortColumnDeselect(const void* const hal, const uint8_t number)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MatrixKbdHalPortColumnDeselect);
  cmock_call_instance = (CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MatrixKbdHalPortColumnDeselect_CallInstance);
  Mock.MatrixKbdHalPortColumnDeselect_CallInstance = CMock_Guts_MemNext(Mock.MatrixKbdHalPortColumnDeselect_CallInstance);
  if (Mock.MatrixKbdHalPortColumnDeselect_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.MatrixKbdHalPortColumnDeselect_FinalReturn;
    memcpy((void*)(&Mock.MatrixKbdHalPortColumnDeselect_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(MatrixKbdHalErr_e[sizeof(cmock_call_instance->ReturnVal) == sizeof(MatrixKbdHalErr_e) ? 1 : -1])); /* add MatrixKbdHalErr_e to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.MatrixKbdHalPortColumnDeselect_CallbackBool &&
      Mock.MatrixKbdHalPortColumnDeselect_CallbackFunctionPointer != NULL)
  {
    MatrixKbdHalErr_e cmock_cb_ret = Mock.MatrixKbdHalPortColumnDeselect_CallbackFunctionPointer(hal, number, Mock.MatrixKbdHalPortColumnDeselect_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_hal)
  {
    UNITY_SET_DETAILS(CMockString_MatrixKbdHalPortColumnDeselect,CMockString_hal);
    if (cmock_call_instance->Expected_hal == NULL)
      { UNITY_TEST_ASSERT_NULL(hal, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_hal, hal, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_number)
  {
    UNITY_SET_DETAILS(CMockString_MatrixKbdHalPortColumnDeselect,CMockString_number);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_number, number, cmock_line, CMockStringMismatch);
  }
  if (Mock.MatrixKbdHalPortColumnDeselect_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.MatrixKbdHalPortColumnDeselect_CallbackFunctionPointer(hal, number, Mock.MatrixKbdHalPortColumnDeselect_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_MatrixKbdHalPortColumnDeselect(CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE* cmock_call_instance, const void* const hal, const uint8_t number);
void CMockExpectParameters_MatrixKbdHalPortColumnDeselect(CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE* cmock_call_instance, const void* const hal, const uint8_t number)
{
  cmock_call_instance->Expected_hal = hal;
  cmock_call_instance->IgnoreArg_hal = 0;
  cmock_call_instance->Expected_number = number;
  cmock_call_instance->IgnoreArg_number = 0;
}

void MatrixKbdHalPortColumnDeselect_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, MatrixKbdHalErr_e cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE));
  CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MatrixKbdHalPortColumnDeselect_CallInstance = CMock_Guts_MemChain(Mock.MatrixKbdHalPortColumnDeselect_CallInstance, cmock_guts_index);
  Mock.MatrixKbdHalPortColumnDeselect_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.MatrixKbdHalPortColumnDeselect_IgnoreBool = (char)1;
}

void MatrixKbdHalPortColumnDeselect_CMockStopIgnore(void)
{
  if(Mock.MatrixKbdHalPortColumnDeselect_IgnoreBool)
    Mock.MatrixKbdHalPortColumnDeselect_CallInstance = CMock_Guts_MemNext(Mock.MatrixKbdHalPortColumnDeselect_CallInstance);
  Mock.MatrixKbdHalPortColumnDeselect_IgnoreBool = (char)0;
}

void MatrixKbdHalPortColumnDeselect_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const void* const hal, const uint8_t number, MatrixKbdHalErr_e cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE));
  CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MatrixKbdHalPortColumnDeselect_CallInstance = CMock_Guts_MemChain(Mock.MatrixKbdHalPortColumnDeselect_CallInstance, cmock_guts_index);
  Mock.MatrixKbdHalPortColumnDeselect_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_MatrixKbdHalPortColumnDeselect(cmock_call_instance, hal, number);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(MatrixKbdHalErr_e[sizeof(cmock_to_return) == sizeof(MatrixKbdHalErr_e) ? 1 : -1])); /* add MatrixKbdHalErr_e to :treat_as_array if this causes an error */
}

void MatrixKbdHalPortColumnDeselect_AddCallback(CMOCK_MatrixKbdHalPortColumnDeselect_CALLBACK Callback)
{
  Mock.MatrixKbdHalPortColumnDeselect_IgnoreBool = (char)0;
  Mock.MatrixKbdHalPortColumnDeselect_CallbackBool = (char)1;
  Mock.MatrixKbdHalPortColumnDeselect_CallbackFunctionPointer = Callback;
}

void MatrixKbdHalPortColumnDeselect_Stub(CMOCK_MatrixKbdHalPortColumnDeselect_CALLBACK Callback)
{
  Mock.MatrixKbdHalPortColumnDeselect_IgnoreBool = (char)0;
  Mock.MatrixKbdHalPortColumnDeselect_CallbackBool = (char)0;
  Mock.MatrixKbdHalPortColumnDeselect_CallbackFunctionPointer = Callback;
}

void MatrixKbdHalPortColumnDeselect_CMockIgnoreArg_hal(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MatrixKbdHalPortColumnDeselect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_hal = 1;
}

void MatrixKbdHalPortColumnDeselect_CMockIgnoreArg_number(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortColumnDeselect_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MatrixKbdHalPortColumnDeselect_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_number = 1;
}

MatrixKbdHalErr_e MatrixKbdHalPortRowStateGet(const void* const hal, const uint8_t number, bool* const data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MatrixKbdHalPortRowStateGet);
  cmock_call_instance = (CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MatrixKbdHalPortRowStateGet_CallInstance);
  Mock.MatrixKbdHalPortRowStateGet_CallInstance = CMock_Guts_MemNext(Mock.MatrixKbdHalPortRowStateGet_CallInstance);
  if (Mock.MatrixKbdHalPortRowStateGet_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.MatrixKbdHalPortRowStateGet_FinalReturn;
    memcpy((void*)(&Mock.MatrixKbdHalPortRowStateGet_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(MatrixKbdHalErr_e[sizeof(cmock_call_instance->ReturnVal) == sizeof(MatrixKbdHalErr_e) ? 1 : -1])); /* add MatrixKbdHalErr_e to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.MatrixKbdHalPortRowStateGet_CallbackBool &&
      Mock.MatrixKbdHalPortRowStateGet_CallbackFunctionPointer != NULL)
  {
    MatrixKbdHalErr_e cmock_cb_ret = Mock.MatrixKbdHalPortRowStateGet_CallbackFunctionPointer(hal, number, data, Mock.MatrixKbdHalPortRowStateGet_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_hal)
  {
    UNITY_SET_DETAILS(CMockString_MatrixKbdHalPortRowStateGet,CMockString_hal);
    if (cmock_call_instance->Expected_hal == NULL)
      { UNITY_TEST_ASSERT_NULL(hal, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_hal, hal, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_number)
  {
    UNITY_SET_DETAILS(CMockString_MatrixKbdHalPortRowStateGet,CMockString_number);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_number, number, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_MatrixKbdHalPortRowStateGet,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_INT_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.MatrixKbdHalPortRowStateGet_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.MatrixKbdHalPortRowStateGet_CallbackFunctionPointer(hal, number, data, Mock.MatrixKbdHalPortRowStateGet_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)data, (const void*)cmock_call_instance->ReturnThruPtr_data_Val,
      cmock_call_instance->ReturnThruPtr_data_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_MatrixKbdHalPortRowStateGet(CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE* cmock_call_instance, const void* const hal, const uint8_t number, bool* const data);
void CMockExpectParameters_MatrixKbdHalPortRowStateGet(CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE* cmock_call_instance, const void* const hal, const uint8_t number, bool* const data)
{
  cmock_call_instance->Expected_hal = hal;
  cmock_call_instance->IgnoreArg_hal = 0;
  cmock_call_instance->Expected_number = number;
  cmock_call_instance->IgnoreArg_number = 0;
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->IgnoreArg_data = 0;
  cmock_call_instance->ReturnThruPtr_data_Used = 0;
}

void MatrixKbdHalPortRowStateGet_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, MatrixKbdHalErr_e cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE));
  CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MatrixKbdHalPortRowStateGet_CallInstance = CMock_Guts_MemChain(Mock.MatrixKbdHalPortRowStateGet_CallInstance, cmock_guts_index);
  Mock.MatrixKbdHalPortRowStateGet_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.MatrixKbdHalPortRowStateGet_IgnoreBool = (char)1;
}

void MatrixKbdHalPortRowStateGet_CMockStopIgnore(void)
{
  if(Mock.MatrixKbdHalPortRowStateGet_IgnoreBool)
    Mock.MatrixKbdHalPortRowStateGet_CallInstance = CMock_Guts_MemNext(Mock.MatrixKbdHalPortRowStateGet_CallInstance);
  Mock.MatrixKbdHalPortRowStateGet_IgnoreBool = (char)0;
}

void MatrixKbdHalPortRowStateGet_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const void* const hal, const uint8_t number, bool* const data, MatrixKbdHalErr_e cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE));
  CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MatrixKbdHalPortRowStateGet_CallInstance = CMock_Guts_MemChain(Mock.MatrixKbdHalPortRowStateGet_CallInstance, cmock_guts_index);
  Mock.MatrixKbdHalPortRowStateGet_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_MatrixKbdHalPortRowStateGet(cmock_call_instance, hal, number, data);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(MatrixKbdHalErr_e[sizeof(cmock_to_return) == sizeof(MatrixKbdHalErr_e) ? 1 : -1])); /* add MatrixKbdHalErr_e to :treat_as_array if this causes an error */
}

void MatrixKbdHalPortRowStateGet_AddCallback(CMOCK_MatrixKbdHalPortRowStateGet_CALLBACK Callback)
{
  Mock.MatrixKbdHalPortRowStateGet_IgnoreBool = (char)0;
  Mock.MatrixKbdHalPortRowStateGet_CallbackBool = (char)1;
  Mock.MatrixKbdHalPortRowStateGet_CallbackFunctionPointer = Callback;
}

void MatrixKbdHalPortRowStateGet_Stub(CMOCK_MatrixKbdHalPortRowStateGet_CALLBACK Callback)
{
  Mock.MatrixKbdHalPortRowStateGet_IgnoreBool = (char)0;
  Mock.MatrixKbdHalPortRowStateGet_CallbackBool = (char)0;
  Mock.MatrixKbdHalPortRowStateGet_CallbackFunctionPointer = Callback;
}

void MatrixKbdHalPortRowStateGet_CMockReturnMemThruPtr_data(UNITY_LINE_TYPE cmock_line, bool const* data, size_t cmock_size)
{
  CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MatrixKbdHalPortRowStateGet_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_data_Used = 1;
  cmock_call_instance->ReturnThruPtr_data_Val = data;
  cmock_call_instance->ReturnThruPtr_data_Size = cmock_size;
}

void MatrixKbdHalPortRowStateGet_CMockIgnoreArg_hal(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MatrixKbdHalPortRowStateGet_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_hal = 1;
}

void MatrixKbdHalPortRowStateGet_CMockIgnoreArg_number(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MatrixKbdHalPortRowStateGet_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_number = 1;
}

void MatrixKbdHalPortRowStateGet_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_MatrixKbdHalPortRowStateGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.MatrixKbdHalPortRowStateGet_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

